import { ExperienceSectionType } from '@/lib/types/sections';

export const experienceSection: ExperienceSectionType = {
  title: "where i've worked",
  experiences: [
    {
      company: 'Curly Blue',
      companyUrl: 'https://curlyblue.com/',
      role: 'Senior Game Developer',
      started: 'March 2025',
      upto: 'Present',
      tasks: [
        'Implemented responsive combat mechanics, designed horror-themed enemy AI, and handled real-time multiplayer syncing using Photon.',
        'I optimized performance for stable high FPS in VR, ensuring comfort and responsiveness.',
        'I also mentored junior developers, reviewed code, and helped maintain code quality. My work was key to delivering an immersive, high-quality multiplayer VR experience.',
        'Optimize performance for Quest 2 to achieve stable frame rates and pass Meta Quest VRC.',
        'Worked closely with artists, designers, and testers to iterate on mechanics and ensure a polished player experience.',
        'Developed internal tools for rapid content iteration and level design.'
      ],
    },
    {
      company: 'PIPEFLARE',
      companyUrl: 'https://pipeflare.io/',
      role: 'Senior Game Developer',
      started: 'November 2020',
      upto: 'February 2025',
      tasks: [
        'Worked on both back-end (BE) and front-end (FE) development to define and implement the game architecture.',
        'Built the Pipeflare SDK to facilitate seamless communication between BE and FE components.',
        'Integrated graphic assets, animations, UI elements, and particle systems to deliver a polished and fully functional game.',
        'Optimized game size and performance for smooth gameplay and efficient resource use.',
        'Researched and implemented strategies to continuously improve game features and performance.',
        'Designed and implemented a gaming ecosystem with blockchain-enabled reward systems.',
        'Developed smart contracts and decentralized applications (dApps) with Web3 integration.',
        'Built RESTful APIs using Laravel to support Unity projects and ensure smooth data exchange.',
        'Collaborated with cross-functional teams to deliver secure and scalable dApps.',
        'Led a team of four developers, managing task allocation, time planning, and code reviews.',
        'Provided mentorship to junior developers, fostering skill development and efficient workflows.',
        'Wrote comprehensive documentation to manage the game development process, track progress, and define future plans.',
        'Prepared detailed reports and presentations for the CEO, including revenue tracking, game quality reviews, and new project proposals.',
        'Managed the game repository using Git for version control and collaboration.',
        'Uploaded and managed the company’s accounts on Google, iOS, and advertising platforms.',
        'Monitored game performance, crash reports, reviews, and ratings to ensure quality and stability.',
        'Provided innovative ideas and developed strategic plans for new and upcoming projects.',
      ],
    },
    {
      company: 'ATHENA STUDIO',
      companyUrl: 'https://athena.studio/',
      role: 'Unity Developer',
      started: 'June 2020',
      upto: 'November 2020',
      tasks: [
        "Collaborated closely with designers and artists to bring game concepts to life, ensuring seamless integration of visual and gameplay elements.",
        "Collaborated closely with QA to deliver game in time.",
        "Optimizing the game performance to run smoothly.",
        "Optimizing the game to reduce size.",
        "Building the android/ios library to integrate 3rd Service.",
        "Having experience in Firebase for analytics, remote config, authentication.",
        "Having experience in uploading the game on Google Play, or Appstore.",
        "Having experience in implementing the 3rd-party such as ADS, IAP, HelpShift, LeaderBoard, etc.",
      ],
    },
    {
      company: 'EYECLICK VN STUDIO',
      companyUrl: 'https://www.eyeclick.com/',
      role: 'Unity Developer',
      started: 'August 2018',
      upto: 'June 2020',
      tasks: [
        'Responsible for developing game logic and mechanics using C#',
        'Develop rapid prototypes of the game logic and mechanics based on a game design document.',
        'Implementing the graphic assets, animations, UI elements, particle system to deliver a fully working game.',
        'Manage the game\'s infrastructure and logic.',
        'Optimizing the game to run smoothly in Tikerboard',
        'Using Android Studio to build the android library',
        'Using Astra or Kinect camera to make the game that needs body detection',
        'Corporating with Israeli team to make the general loading screen for all games. Implementing SDK to communicate with the OS',
        'Adjusting the interaction to match the requirement of each game. The interaction was sent from OS to the game',
        'Researching the way to improve the OS which affects the frame rate of the game',
        "Supporting team members to deliver high quality products in time.",
      ],
    },
    {
      company: 'GAMELOFT',
      companyUrl: 'https://www.gameloft.com/',
      role: 'C++ GAME PROGRAMMER',
      started: 'March 2018',
      upto: 'August 2018',
      tasks: [
        'Porting Game.',
        'Fix bugs and Checking Crash.',
        'Finding solutions to resolve crashes.',
      ],
    },
    {
      company: 'VNG CORPORATION',
      companyUrl: 'https://vng.com.vn/',
      role: 'Fresher Unity Developer',
      started: 'November 2017',
      upto: 'March 2018',
      tasks: [
        'Game development.',
        'Studying and working with a team to develop a product that was designed by our team with support from the project manager.',
      ],
    },
  ],
};
